[package]
name = "peri-rusty"
version = "0.1.0"
authors = ["Bryn Bayliss <brynbayliss@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1"
futures = "0.1.14"
fantoccini = "0.11.9"
